include: package:pedantic/analysis_options.1.9.0.yaml

analyzer:
  exclude: 
    - build/**
    - lib/data/entities/**.g.dart

  strong-mode:
    implicit-casts: false
  enable-experiment:
    - control-flow-collections