name: my_ministry
description: My Ministry - an open source project for managing activities related to the service of God.
homepage: https://gitlab.com/dimoshka/my-ministry
repository: https://gitlab.com/dimoshka/my-ministry.git
issue_tracker: https://gitlab.com/dimoshka/my-ministry/-/issues
documentation: https://gitlab.com/dimoshka/my-ministry/-/blob/master/README.md
version: 1.0.0+1

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  hive: ^1.4.1+1
  hive_flutter: ^0.3.0+2
  flutter_bloc: ^3.2.0
  provider: ^4.0.5

dev_dependencies:
  #flutter_test:
  #  sdk: flutter
  hive_generator: ^0.7.0+2
  build_runner: ^1.8.1
  pedantic: ^1.9.0

flutter:
  uses-material-design: true